<a href="https://colab.research.google.com/github/yuukimotai/KikagakuRyuu_Course/blob/main/kikagakuryuu3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

$$w = (X^TX)^{-1}X^Ty$$
これを実装するために、  
・ベクトルの定義  
・行列の定義  
・転置.  
・逆行列.  
・行列積  
が必要。

In [1]:
##  重回帰分析の実装
### 行列演算の基礎
import numpy as np

x = np.array([[[1],[2],[3]]])
print(x)

[[[1]
  [2]
  [3]]]


In [2]:
###行列の定義
X = np.array([[1, 2],[3,4]])
X

array([[1, 2],
       [3, 4]])

In [3]:
### 転置
X.T

array([[1, 3],
       [2, 4]])

In [5]:
### 逆行列
X_inv = np.linalg.inv(X)

In [8]:
### 行列積
XX_inv = np.dot(X, X_inv)
print(XX_inv)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [9]:
###　よくある間違い これだと転置ができない
x = np.array([1,2,3])
x

array([1, 2, 3])

In [11]:
### 転置をする場合、ベクトルは二重カッコで囲む必要がある
x = np.array([[1,2,3]])
print(x.T)
print(x.shape)

[[1]
 [2]
 [3]]
(1, 3)


In [15]:
row, col = x.shape
print("行数 (row):", row)
print("列数 (col):", col)

行数 (row): 1
列数 (col): 3


In [17]:
for x in X_inv:
    print(x)

[-2.  1.]
[ 1.5 -0.5]


In [28]:
## 演習
X = np.array([[1,2,3],
              [1,2,5],
              [1,3,4],
              [1,5,9]])
y = np.array([[1],
              [5],
              [6],
              [8]])
XtX = np.dot(X.T, X)
linalg = np.linalg.inv(XtX)
#print(linalg)
Xty = np.dot(X.T, y)
XtXXty = np.dot(linalg, Xty)
print(XtXXty)# wの事


[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]


In [31]:
### scikit-learnで実装
import numpy as np
from sklearn.linear_model import LinearRegression

model = LinearRegression()



array([[0.        , 0.71428571, 0.57142857]])

In [35]:
###　モデルの学習(パラメータの調整)
model.fit(X, y)

LinearRegression()

In [36]:
model.coef_

array([[0.        , 0.71428571, 0.57142857]])

In [32]:
model.intercept_

array([-0.14285714])

In [34]:
# 精度　（決定係数）
model.score(X, y)

0.6923076923076924

In [38]:
x = np.array([[1,2,3]])

In [40]:
y_pred = model.predict(x)
y_pred

array([[3.]])