<a href="https://colab.research.google.com/github/yuukimotai/KikagakuRyuu_Course/blob/main/kikagakuryuu2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### キカガク流　中級
スカラー変数: 小文字、細文字(x)  
スカラー定数: 大文字、細文字(N)  
ベクトル: 小文字、太文字$(\boldsymbol{x})$  
行列: 大文字、太文字$(\boldsymbol{X})$
として表現する。

In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print()
print(a*b)

print(a.T, b.T)

[5 7 9]

[ 4 10 18]
[1 2 3] [4 5 6]
[1 2 3] [4 5 6]


In [ ]:
a1 = np.array([[1,2],[3,4]])
b2 = np.array([[5,6],[7,8]])
print(np.dot(a1,b2))# 要、手計算の順番

[[19 22]
 [43 50]]


## 行列積が成り立つ条件
(N×M) (O×P)　という行列積の場合、
MとOが等しいことが条件。
結果はN×Pの行列として取得される

In [ ]:
eye1 = np.eye(2)
print(eye1)

[[1. 0.]
 [0. 1.]]


## ベクトルで微分
$$(1)\frac{\partial}{\partial\boldsymbol{x}}(c) = \boldsymbol{0}(ゼロベクトル)$$
$$(2)\frac{\partial}{\partial\boldsymbol{x}}(\boldsymbol{b}^{T}x) = \boldsymbol{b}$$
$$(3)\frac{\partial}{\partial\boldsymbol{x}}(\boldsymbol{x}^{T}A\boldsymbol{x}) = (A + A^{T})\boldsymbol{x}$$

###モデルを決める
動画の例
家賃(y) - ひろさ(x1),距離(x2)...治安(xm)  
${\hat y} = (w_1x_1 + w_2x_2 + .... + w_mx_m) + b(x_0)$
$$
\begin{bmatrix}
x_0 & x_1 & \cdots & x_m
\end{bmatrix}
\begin{bmatrix}
w_0 \\ w_1 \\ \vdots \\ w_m
\end{bmatrix}
= \boldsymbol{x}^{T}\boldsymbol{W}
 $$

### 評価関数を決める
$$(実測値-予測値)^2$$
$$ \boldsymbol{L} = \sum{(y_n - \widehat y)^2}$$
$$=(\boldsymbol{y}-\boldsymbol{ \widehat y})^{T}(\boldsymbol{y}-\boldsymbol{ \widehat y})$$

### 評価関数(誤差)
$$
{\widehat{y}}=
\begin{bmatrix}
{\hat{y_1}} \\
{\hat{y_2}} \\
{\hat{y_3}} \\
\vdots \\
{\widehat y_m}
\end{bmatrix}
=
\begin{bmatrix}
{x_1^TW} \\
{x_2^TW} \\
{x_3^TW} \\
\vdots \\
{x_m^TW}
\end{bmatrix}
=
\begin{bmatrix}
{x_1^T} \\
{x_2^T} \\
{x_3^T} \\
\vdots \\
{x_m^T}
\end{bmatrix}
W
=
\begin{bmatrix}
x_{10} & x_{11} & x_{12} & \cdots & x_{1m} \\
x_{20} & x_{21} & x_{22} & \cdots & x_{2m} \\
x_{20} & x_{21} & x_{22} & \cdots & x_{3m} \\
\vdots & \vdots  & \vdots & \ddots & \vdots\\
x_{n0} & x_{n1} & x_{n3} & \cdots & x_{nm} \\
\end{bmatrix}
= X\boldsymbol{W}
 $$

 $$ {\hat y} = (y - {Xw})^T(y - {Xw})
 = {\hat y} = [(y^T - ({Xw})^T)](y - {Xw})$$
 $$L = y^Ty - 2y^TXW + W^TX^TXW$$
 上記の式について、微分する際はWに着目する。
 そうすると、以下のような式にまとめられる。  
 ※行列のサイズ感の項参照
 $$ = C + b^TW + W^TAW$$


上記の式を使って微分する場合、以下のようになる。
$$\frac{\partial}{\partial{W}}(L)=0$$
$$→\frac{\partial}{\partial{W}}(C + b^TW + W^TAW)=0$$
$$→\frac{\partial}{\partial{W}}(C) + \frac{\partial}{\partial{W}}(b^TW) + \frac{\partial}{\partial{W}}(W^TAW)$$
$$→ -2X^Ty + {X^TX + (X^TX)^T}W = 0$$
$$→ -2X^Ty + 2X^TXW = 0$$
$$→ 2X^TXW = 2X^Ty$$
$$I = (X^TX)^{-1} として両辺にかける$$
$$→IW = IX^Ty$$
$$→ W = (X^TX)^{-1}X^Ty$$
#### 多重共線性に注意